# Generated by Django 4.2.7 on 2025-11-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('card', 'Card')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_token', models.CharField(blank=True, max_length=200)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.folio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['folio', '-created_at'], name='payments_pa_folio_i_e1fab7_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx')],
            },
        ),
    ]
