# Generated by Django 4.2.7 on 2025-11-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('per_unit', 'Per Unit'), ('variable', 'Variable (Menu Items)')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('tax', 'Tax'), ('discount', 'Discount'), ('surcharge', 'Surcharge')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage value (e.g., 16.00 for 16%)', max_digits=5)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Optional conditions (e.g., {"peak_hours": "18:00-22:00"})')),
                ('priority', models.IntegerField(default=0, help_text='Lower values apply first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='services.service')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
