# Generated by Django 4.2.7 on 2025-11-01 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('charge_created', 'Charge Created'), ('charge_modified', 'Charge Modified'), ('payment_created', 'Payment Created'), ('payment_processed', 'Payment Processed'), ('payment_failed', 'Payment Failed'), ('folio_settled', 'Folio Settled'), ('folio_cancelled', 'Folio Cancelled')], max_length=50)),
                ('entity_type', models.CharField(help_text='Model name (e.g., Charge, Payment)', max_length=50)),
                ('entity_id', models.IntegerField(help_text='ID of the affected entity')),
                ('actor_name', models.CharField(help_text='Name of actor (user/system)', max_length=200)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
